name: Cypress Tests using Cypress Docker Image with allure-report

on:
    push:
        branches: [master]

jobs:
    cypress-run:
        runs-on: ubuntu-20.04
        # Cypress Docker image with Chrome v78
        # and Firefox v70 pre-installed
        container: cypress/browsers:node12.13.0-chrome78-ff70
        steps:
            - uses: actions/checkout@v2
            - uses: cypress-io/github-action@v4
              with:
                  browser: chrome
            # - name: Upload artifact allure-report
            #   uses: actions/upload-artifact@v1
            #   if: always()
            #   with:
            #       name: allure-report
            #       path: ./reports/ui/allure-report
            # - name: Deploy report
            #   uses: JamesIves/github-pages-deploy-action@3.1.0
            #   if: always()
            #   with:
            #       ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
            #       BRANCH: master # The branch the action should deploy to.
            #       FOLDER: allure-report # The folder the action should deploy.
            #       TARGET_FOLDER: docs # The folder the action should deploy to.
