name: Cypress Tests using Cypress Docker Image with allure-report

on:
    push:
        branches: [master]

jobs:
    cypress-run:
        runs-on: ubuntu-20.04 # Choosing OS
        container: cypress/browsers:node12.18.3-chrome87-ff82
        strategy:
          matrix:
            node-version: [14.17.0]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
            - name: Checkout
              uses: actions/checkout@v2
          # trying to install npm packages
        - run: npm i npm@latest
        - run: npm i
        # Install NPM dependencies, cache them correctly
        # and run all Cypress tests
        - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
              # Specify Browser since container image is compile with Firefox
              browser: chrome
        - name: Upload artifact allure-report
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: allure-report
            path: ./reports/ui/allure-report
        - name: Deploy report
          uses: JamesIves/github-pages-deploy-action@3.1.0
          if: always()
          with:
            ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
            BRANCH: master # The branch the action should deploy to.
            FOLDER: allure-report # The folder the action should deploy.
            TARGET_FOLDER: docs # The folder the action should deploy to.